---
- name: Manage httpd.conf
  hosts: web
  become: true
  handlers:
    - name: Restart Apache service
      listen: restart_apache_handler
      ansible.builtin.service:
        name: httpd
        state: restarted
  tasks:
    - name: Copy Apache configuration file
      ansible.builtin.copy:
        src: httpd.conf
        dest: /etc/httpd/conf/httpd.conf
        mode: "0644"
        owner: apache
        group: apache
      notify:
        - restart_apache_handler
