---
- name: Fill motd file with host data
  hosts: node1
  become: true
  handlers:
    - name: Output info about MOTD
      listen: motd_changed_handler
      ansible.builtin.debug:
        msg: "The Message of the Day was updated! SSH to node1 and check the content."
  tasks:
    - name: Deploy message of the day file
      ansible.builtin.template:
        src: motd-facts.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: "0644"
      notify: motd_changed_handler

    - name: Add script to /etc/profile.d for MOTD
      ansible.builtin.copy:
        content: cat /etc/motd
        dest: /etc/profile.d/motd.sh
        owner: root
        group: root
        mode: "0755"
