---
- name: Webserver configuration
  hosts: web
  become: true
  tasks:
    - name: Copy web.html
      ansible.builtin.copy:
        src: "{{ stage }}_web.html"
        dest: /var/www/html/index.html
        mode: "0644"
        owner: apache
        group: apache
